site_name: GLOBALISE Lab
repo_name: "globalise-huygens/lab.globalise.huygens.knaw.nl/"
repo_url: "https://github.com/globalise-huygens/lab.globalise.huygens.knaw.nl/"

theme:
  name: material
  # logo: static/globalise_g.svg
  icon:
    logo: material/flask
  features:
    # - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top

nav:
  - Introduction: index.md
  #- About: about.md
  - "Ongoing experiments":
      - "Transcriptions viewer": ongoing-experiments/htr-viewer.md
      - "Thesaurus concepts browser": ongoing-experiments/skosmos-concept-browser.md
      - "Places visualization": ongoing-experiments/places-visualization.md
  - "Completed experiments":
      - "Word Embeddings": finished-experiments/word-embeddings.md
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - footnotes
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
extra_css:
  - stylesheets/extra.css
extra:
  #   social:
  #     - icon: fontawesome/brands/mastodon
  #       link: https://fosstodon.org/@squidfunk
  generator: false
copyright: <p>
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License"
  style="border-width:0" src="https://licensebuttons.net/i/l/by-sa/transparent/ff/ff/ff/88x31.png" /></a><br/>
  <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">The GLOBALISE Lab</span> is an experimental playground by the <a
  xmlns:cc="http://creativecommons.org/ns#" href="https://globalise.huygens.knaw.nl/" property="cc:attributionName"
  rel="cc:attributionURL">GLOBALISE project</a>. Information on this static website is licensed under a <a rel="license"
  href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons BY-SA 4.0 International License</a>.
  </p>
